
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author fbsel
 */
public class txtDosyaAçmaEkrani extends javax.swing.JInternalFrame {

    /**
     * Creates new form txtDosyaAçmaEkrani
     */
    public txtDosyaAçmaEkrani() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonTxtAc = new javax.swing.JButton();
        jButtonKydt = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButtonTxtAc.setText("TXT AÇ");
        jButtonTxtAc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonTxtAcMouseClicked(evt);
            }
        });
        jButtonTxtAc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTxtAcActionPerformed(evt);
            }
        });

        jButtonKydt.setText("KAYDET");
        jButtonKydt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKydtActionPerformed(evt);
            }
        });

        jButton3.setText("TEMİZLE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonTxtAc)
                        .addGap(43, 43, 43)
                        .addComponent(jButtonKydt)
                        .addGap(39, 39, 39)
                        .addComponent(jButton3)
                        .addGap(0, 251, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTxtAc)
                    .addComponent(jButtonKydt)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTxtAcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTxtAcMouseClicked
        try{
            goster();
        } catch (IOException ex) {
            Logger.getLogger(txtDosyaAçmaEkrani.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonTxtAcMouseClicked

    private void jButtonKydtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKydtActionPerformed
       try {
            kaydet();
            JOptionPane.showMessageDialog(this, "Bilgiler guncellendi...");
        } catch (IOException ex) {
            Logger.getLogger(txtDosyaAçmaEkrani.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonKydtActionPerformed

    private void jButtonTxtAcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTxtAcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTxtAcActionPerformed
    public void goster() throws FileNotFoundException, IOException{
        String fileYol = "C:\\Users\\fbsel\\Downloads\\dersler.txt";
        File file=new File(fileYol);
        BufferedReader br=new BufferedReader(new FileReader(file));
        jTextArea1.read(br,null);
        br.close();
        jTextArea1.requestFocus();
        
    }    
    
    public void kaydet() throws IOException{
        String fileYol = "C:\\Users\\fbsel\\Downloads\\dersler.txt";
        File file=new File(fileYol);
        BufferedWriter bufferedWriter=new BufferedWriter(new FileWriter(file));
        jTextArea1.write(bufferedWriter);
        bufferedWriter.close();
        jTextArea1.requestFocus();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonKydt;
    private javax.swing.JButton jButtonTxtAc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
